cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order')
]

orders/models.py
from django.db import models

from accounts.models import User
from shop.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user.full_name} - order id: {self.id}"

    @property
    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        return total
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.IntegerField()
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST
from django.utils import timezone

from .models import Order, OrderItem
from cart.utils.cart import Cart


@login_required
def create_order(request):
    cart = Cart(request)
    order = Order.objects.create(user=request.user)
    for item in cart:
        OrderItem.objects.create(
            order=order, product=item['product'],
            price=item['price'], quantity=item['quantity']
    )
    return redirect('orders:pay_order', order_id=order.id)


@login_required
def checkout(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {'title':'Checkout' ,'order':order}
    return render(request, 'checkout.html', context)


@login_required
def fake_payment(request, order_id):
    cart = Cart(request)
    cart.clear()
    order = get_object_or_404(Order, id=order_id)
    order.status = True
    order.save()
    return redirect('orders:user_orders')


@login_required
def user_orders(request):
    orders = request.user.orders.all()
    context = {'title':'Orders', 'orders': orders}
    return render(request, 'user_orders.html', context)

orders/templates/checkout.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-2"></div>

<div class="col-md-8 border rounded p-3">
    <h3 class="text-muted">Your Order Amount is: ${{order.get_total_price}}</h3>
    <hr>
    <p><b>Do you want to continue and pay?</b></p>
    <a href="{% url 'cart:show_cart' %}" class="btn btn-danger">Back To Cart</a>
    <a href="{% url 'orders:create_order' %}" class="btn btn-outline-success">Continue and pay</a>
<div class="col-md-2"></div>

{% endblock %}

orders/templates/user_orders.html
{% extends "base.html" %}

{% block content %}

{% if orders %}
{% for order in orders %}
<div class="col-md-7 mb-4 border rounded p-3">
<!-- order id on right -->
<b style="float: right;">Order Id: {{ order.id }}</b>
<!-- order payment status -->
{% if order.status %}
    <h4><b class="text-success">Successful</b></h4>
{% else %}
    <h3><b class="text-danger">Cancelled</b></h3>
{% endif %}
<div class="text-muted border-top pt-2"></div>
{% for item in order.items.all  %}
    <div class="border-bottom p-2">
        <p>product: <a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">{{item.product.title}}</a></p>
        <p>Price: ${{item.price}}</p>
        <p>quantity: {{item.quantity}}</p>
    </div>
{% endfor %}
<b>Total price: ${{ order.get_total_price }}</b>
</div>
{% endfor %}
{% else %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 mt-5 pt-5 text-center">
      <br>
      <h3 class="text-muted text-capitalize">Orders list is empty..!</h3>
      <a href="/" class="text-primary text-decoration-none">Back</a>
    </div>
    <div class="col-md-2"></div>
</div>
{% endif %}

{% endblock %}