accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from .managers import UserManager
from shop.models import Product


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100)    
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    likes = models.ManyToManyField(Product, blank=True, related_name='likes')
    # set a manager role for shop manager to access orders and products
    is_manager = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def get_likes_count(self):
        return self.likes.count()

accounts/forms.py
from django import forms

from .models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    full_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'full name'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class ManagerLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'email'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'password'}
        )
    )


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['full_name', 'email']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from .forms import UserRegistrationForm, UserLoginForm, ManagerLoginForm, EditProfileForm
from accounts.models import User


def create_manager():
    """
    to execute once on startup:
    this function will call in online_shop/urls.py
    """
    if not User.objects.filter(email="manager@example.com").first():
        user = User.objects.create_user(
            "manager@example.com", 'shop manager' ,'managerpass1234'
        )
        # give this user manager role
        user.is_manager = True
        user.save()


def manager_login(request):
    if request.method == 'POST':
        form = ManagerLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None and user.is_manager:
                login(request, user)
                return redirect('dashboard:products')
            else:
                messages.error(
                    request, 'username or password is wrong', 'danger'
                )
                return redirect('accounts:manager_login')
    else:
        form = ManagerLoginForm()
    context = {'form': form}
    return render(request, 'manager_login.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                data['email'], data['full_name'], data['password']
            )
            return redirect('accounts:user_login')
    else:
        form = UserRegistrationForm()
    context = {'title':'Signup', 'form':form}
    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, email=data['email'], password=data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('shop:home_page')
            else:
                messages.error(
                    request, 'username or password is wrong', 'danger'
                )
                return redirect('accounts:user_login')
    else:
        form = UserLoginForm()
    context = {'title':'Login', 'form': form}
    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')


def edit_profile(request):
    form = EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your profile has been updated', 'success')
        return redirect('accounts:edit_profile')
    else:
        form = EditProfileForm(instance=request.user)
    context = {'title':'Edit Profile', 'form':form}
    return render(request, 'edit_profile.html', context)

accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Edit Profile</h3>
            <hr>
            {{ form|crispy  }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/email_template.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Login</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
            </div>
            <div class="mt-2 mb-2">
                <small class="">
                    <a class="text-decoration-none text-danger" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                New Here? <a class="text-decoration-none" href="{% url 'accounts:user_register' %}">Create account</a>
            </small>
        </div>
    </div>
{% endblock %}

accounts/templates/manager_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
  </head>
  <body>
    <main class="container">
      <div class="row mt-5 text-capitalize">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <form method="post" class="mt-5 pt-5">
            {% csrf_token %}
            <h2>Dashboard</h2>
            {{ form }}
            <button class="w-100 btn btn-primary mt-3" type="submit">Sign In</button>
          </form>
          <p class="text-muted mt-3"><a href="{% url 'shop:home_page' %}">Back to shop</a></p>
        </div>
        <div class="col-md-4"></div>
      </div>
    </main>
  </body>
</html>

accounts/templates/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Reset Password</h3>
            <hr>
            <p class="text-danger">Please enter your email that you used in your account.</p>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6 alert alert-success">
        Your Password Has Been Set.
    </div>
    <a href="{% url 'accounts:user_login' %}" class="">Login Here</a>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Reset Password</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/password_reset_done.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6 alert alert-info">
        An Email has been sent with instrunctions to reset your password!
    </div>
{% endblock %}

accounts/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Create Account</h3>
            <hr>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-primary w-100 mt-2" type="submit">Submit</button>
            </div>
        </form>
        <div class="mt-3">
            <small class="text-muted">
                Already have an account? <a href="{% url 'accounts:user_login' %}">Login</a>
            </small>
        </div>
    </div>
{% endblock %}