accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('products', views.products, name='products'),
    path('products/delete/<int:id>', views.delete_product, name='delete_product'),
    path('products/edit/<int:id>', views.edit_product, name='edit_product'),
    path('orders', views.orders, name='orders'),
    path('orders/detail/<int:id>', views.order_detail, name='order_detail'),
    path('add-product/', views.add_product, name='add_product'),
    path('add-category/', views.add_category, name='add_category'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order')
]

dashboard/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

from accounts.models import User
from shop.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user.full_name} - order id: {self.id}"

    @property
    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        return total
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.IntegerField()
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

dashboard/forms.py
from django import forms
from django.forms import ModelForm

from shop.models import Product, Category


class AddProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'image', 'title','description', 'price']

    def __init__(self, *args, **kwargs):
        super(AddProductForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class AddCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'sub_category', 'is_sub']
    

    def __init__(self, *args, **kwargs):
        super(AddCategoryForm, self).__init__(*args, **kwargs)
        self.fields['is_sub'].widget.attrs['class'] = 'form-check-input'
        self.fields['sub_category'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['class'] = 'form-control'


class EditProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'image', 'title','description', 'price']

    def __init__(self, *args, **kwargs):
        super(EditProductForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404

from shop.models import Product
from accounts.models import User
from orders.models import Order, OrderItem
from .forms import AddProductForm, AddCategoryForm, EditProductForm


def is_manager(user):
    try:
        if not user.is_manager:
            raise Http404
        return True
    except:
        raise Http404


@user_passes_test(is_manager)
@login_required
def products(request):
    products = Product.objects.all()
    context = {'title':'Products' ,'products':products}
    return render(request, 'products.html', context)


@user_passes_test(is_manager)
@login_required
def add_product(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product added Successfuly!')
            return redirect('dashboard:add_product')
    else:
        form = AddProductForm()
    context = {'title':'Add Product', 'form':form}
    return render(request, 'add_product.html', context)


@user_passes_test(is_manager)
@login_required
def delete_product(request, id):
    product = Product.objects.filter(id=id).delete()
    messages.success(request, 'product has been deleted!', 'success')
    return redirect('dashboard:products')


@user_passes_test(is_manager)
@login_required
def edit_product(request, id):
    product = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product has been updated', 'success')
            return redirect('dashboard:products')
    else:
        form = EditProductForm(instance=product)
    context = {'title': 'Edit Product', 'form':form}
    return render(request, 'edit_product.html', context)


@user_passes_test(is_manager)
@login_required
def add_category(request):
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category added Successfuly!')
            return redirect('dashboard:add_category')
    else:
        form = AddCategoryForm()
    context = {'title':'Add Category', 'form':form}
    return render(request, 'add_category.html', context)


@user_passes_test(is_manager)
@login_required
def orders(request):
    orders = Order.objects.all()
    context = {'title':'Orders', 'orders':orders}
    return render(request, 'orders.html', context)


@user_passes_test(is_manager)
@login_required
def order_detail(request, id):
    order = Order.objects.filter(id=id).first()
    items = OrderItem.objects.filter(order=order).all()
    context = {'title':'order detail', 'items':items, 'order':order}
    return render(request, 'order_detail.html', context)

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST
from django.utils import timezone

from .models import Order, OrderItem
from cart.utils.cart import Cart


@login_required
def create_order(request):
    cart = Cart(request)
    order = Order.objects.create(user=request.user)
    for item in cart:
        OrderItem.objects.create(
            order=order, product=item['product'],
            price=item['price'], quantity=item['quantity']
    )
    return redirect('orders:pay_order', order_id=order.id)


@login_required
def checkout(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {'title':'Checkout' ,'order':order}
    return render(request, 'checkout.html', context)


@login_required
def fake_payment(request, order_id):
    cart = Cart(request)
    cart.clear()
    order = get_object_or_404(Order, id=order_id)
    order.status = True
    order.save()
    return redirect('orders:user_orders')


@login_required
def user_orders(request):
    orders = request.user.orders.all()
    context = {'title':'Orders', 'orders': orders}
    return render(request, 'user_orders.html', context)

dashboard/templates/add_category.html
{% extends "dashboard.html" %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

{% endblock %}

dashboard/templates/add_product.html
{% extends "dashboard.html" %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

{% endblock %}

dashboard/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
    <div class="row mt-5">
        <div class="col-md-1"></div>
        <!-- content -->
        <div class="col-md-7">
            <h2 class="border-bottom text-capitalize">{{ title }}</h2>
            <div class="p-4">
                <!-- messages -->
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
        <!-- sidebar -->
        <div class="col-md-3 border-start">
            <h3 class="text-muted">Menu</h3>
            <a class="text-decoration-none" href="{% url 'dashboard:products' %}">
                <li class="rounded list-group-item  text-primary">Products</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:add_product' %}">
                <li class="rounded list-group-item mt-2 text-primary">Add New Product</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:add_category' %}">
                <li class="rounded list-group-item mt-2  text-primary">Add New Category</li>
            </a>
            <a class="text-decoration-none" href="{% url 'dashboard:orders' %}">
                <li class="rounded list-group-item mt-2  text-primary">Orders</li>
            </a>
            <hr>
            <a class="text-decoration-none" href="{% url 'shop:home_page' %}">
                <li class="rounded list-group-item bg-primary mt-2  text-white">Back To shop</li>
            </a>
            <a class="text-decoration-none" href="{% url 'accounts:user_logout' %}">
                <li class="rounded list-group-item bg-danger mt-2  text-white">Logout</li>
            </a>
            <div class="text-muted mt-2">You logged in as: {{ request.user.email }}</div>
        </div>
        <div class="col-md-1 "></div>
    </div>
</body>
</html>

dashboard/templates/edit_product.html
{% extends "dashboard.html" %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
    </div>
</form>

{% endblock %}

dashboard/templates/order_detail.html
{% extends "dashboard.html" %}

{% block content %}
{% if order.status %}
    <h4><b class="text-success">Successful</b></h4>
{% else %}
    <h3><b class="text-danger">Cancelled</b></h3>
{% endif %}
{% for item in items  %}
<div class="bg-light rounded border-bottom p-3">
    <p>product:<a class="text-decoration-none" href="{{ item.product.get_absolute_url }}"> {{item.product.title}}</a></p>
    <p>Price: ${{item.price}}</p>
    <p>quantity: {{item.quantity}}</p>
</div>
{% endfor %}
<h4 class="border-top pt-2 text-muted">Total: ${{ order.get_total_price }}</h4>

{% endblock %}

dashboard/templates/orders.html
{% extends "dashboard.html" %}
{% block content %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Id</th>
        <th scope="col">total price</th>
        <th scope="col">status</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for order in orders %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ order.user.full_name }}</td>
        <td>{{ order.id }}</td>
        <td>${{ order.get_total_price }}</td>
        {% if order.status %}
            <td class="text-success">Successful</td>
        {% else %}
            <td class="text-danger">Canceled</td>
        {% endif %}
        <td><a href="{% url 'dashboard:order_detail' order.id %}" class="text-primary text-decoration-none">Detail</a></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  

{% endblock %}

dashboard/templates/products.html
{% extends "dashboard.html" %}

{% block content %}

<table class="table table-striped ">
    <thead class="text-muted">
        <tr>
            <th scope="col">n</th>
            <th scope="col">title</th>
            <th scope="col">price</th>
            <th scope="col">category</th>
            <th scope="col">date</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    {% for product in products %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
        <td>${{ product.price }}</td>
        <td>{{ product.category }}</td>
        <td>{{ product.date_created|date:"M d" }}</td>
        <td><a class="text-danger text-decoration-none" href="{% url 'dashboard:delete_product' product.id %}">Delete</a></td>
        <td><a class="text-info text-decoration-none" href="{% url 'dashboard:edit_product' product.id %}">Edit</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>

{% endblock %}